name: CI Build
on: workflow_dispatch
jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip wheel fairseq
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: Windows whl
          path: fairseq-*.whl
          if-no-files-found: error
