name: CI Build
on: workflow_dispatch
jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: pip wheel https://github.com/VarunGumma/fairseq/archive/refs/heads/main.zip
        continue-on-error: true
      - uses: actions/upload-artifact@v5
        with:
          name: Windows whl
          path: fairseq-*.whl
          if-no-files-found: error
